# Generated by Django 5.0.2 on 2024-02-12 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nxtTransport', '0003_transportrequest_delete_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(max_length=100)),
                ('to_location', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('rider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nxtTransport.user')),
            ],
        ),
    ]
