# Generated by Django 5.0.2 on 2024-02-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nxtTransport', '0005_ride_medium'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportrequest',
            name='status',
            field=models.CharField(default='unapplied', max_length=20),
        ),
    ]
