# Generated by Django 5.0.2 on 2024-02-13 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nxtTransport', '0006_transportrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReqApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('datetime', models.DateTimeField()),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nxtTransport.transportrequest')),
                ('ride_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nxtTransport.ride')),
            ],
        ),
    ]
